/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.facebook.maestro;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum OdsAggregationType implements org.apache.thrift.TEnum {
  ODS_AGGREGATION_TYPE_DEFAULT(1),
  ODS_AGGREGATION_TYPE_AVG(2),
  ODS_AGGREGATION_TYPE_SUM(4),
  ODS_AGGREGATION_TYPE_COUNT(8),
  ODS_AGGREGATION_TYPE_MAX(16),
  ODS_AGGREGATION_TYPE_MIN(32);

  private final int value;

  private OdsAggregationType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static OdsAggregationType findByValue(int value) { 
    switch (value) {
      case 1:
        return ODS_AGGREGATION_TYPE_DEFAULT;
      case 2:
        return ODS_AGGREGATION_TYPE_AVG;
      case 4:
        return ODS_AGGREGATION_TYPE_SUM;
      case 8:
        return ODS_AGGREGATION_TYPE_COUNT;
      case 16:
        return ODS_AGGREGATION_TYPE_MAX;
      case 32:
        return ODS_AGGREGATION_TYPE_MIN;
      default:
        return null;
    }
  }
}
