/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.facebook.maestro;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-7-22")
public class ODSAppValueWithTagsList implements org.apache.thrift.TBase<ODSAppValueWithTagsList, ODSAppValueWithTagsList._Fields>, java.io.Serializable, Cloneable, Comparable<ODSAppValueWithTagsList> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ODSAppValueWithTagsList");

  private static final org.apache.thrift.protocol.TField DATAPOINTS_FIELD_DESC = new org.apache.thrift.protocol.TField("datapoints", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ODSAppValueWithTagsListStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ODSAppValueWithTagsListTupleSchemeFactory());
  }

  public List<ODSAppValueWithTags> datapoints; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DATAPOINTS((short)1, "datapoints");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DATAPOINTS
          return DATAPOINTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DATAPOINTS, new org.apache.thrift.meta_data.FieldMetaData("datapoints", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ODSAppValueWithTags.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ODSAppValueWithTagsList.class, metaDataMap);
  }

  public ODSAppValueWithTagsList() {
  }

  public ODSAppValueWithTagsList(
    List<ODSAppValueWithTags> datapoints)
  {
    this();
    this.datapoints = datapoints;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ODSAppValueWithTagsList(ODSAppValueWithTagsList other) {
    if (other.isSetDatapoints()) {
      List<ODSAppValueWithTags> __this__datapoints = new ArrayList<ODSAppValueWithTags>(other.datapoints.size());
      for (ODSAppValueWithTags other_element : other.datapoints) {
        __this__datapoints.add(new ODSAppValueWithTags(other_element));
      }
      this.datapoints = __this__datapoints;
    }
  }

  public ODSAppValueWithTagsList deepCopy() {
    return new ODSAppValueWithTagsList(this);
  }

  @Override
  public void clear() {
    this.datapoints = null;
  }

  public int getDatapointsSize() {
    return (this.datapoints == null) ? 0 : this.datapoints.size();
  }

  public java.util.Iterator<ODSAppValueWithTags> getDatapointsIterator() {
    return (this.datapoints == null) ? null : this.datapoints.iterator();
  }

  public void addToDatapoints(ODSAppValueWithTags elem) {
    if (this.datapoints == null) {
      this.datapoints = new ArrayList<ODSAppValueWithTags>();
    }
    this.datapoints.add(elem);
  }

  public List<ODSAppValueWithTags> getDatapoints() {
    return this.datapoints;
  }

  public ODSAppValueWithTagsList setDatapoints(List<ODSAppValueWithTags> datapoints) {
    this.datapoints = datapoints;
    return this;
  }

  public void unsetDatapoints() {
    this.datapoints = null;
  }

  /** Returns true if field datapoints is set (has been assigned a value) and false otherwise */
  public boolean isSetDatapoints() {
    return this.datapoints != null;
  }

  public void setDatapointsIsSet(boolean value) {
    if (!value) {
      this.datapoints = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case DATAPOINTS:
      if (value == null) {
        unsetDatapoints();
      } else {
        setDatapoints((List<ODSAppValueWithTags>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case DATAPOINTS:
      return getDatapoints();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case DATAPOINTS:
      return isSetDatapoints();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ODSAppValueWithTagsList)
      return this.equals((ODSAppValueWithTagsList)that);
    return false;
  }

  public boolean equals(ODSAppValueWithTagsList that) {
    if (that == null)
      return false;

    boolean this_present_datapoints = true && this.isSetDatapoints();
    boolean that_present_datapoints = true && that.isSetDatapoints();
    if (this_present_datapoints || that_present_datapoints) {
      if (!(this_present_datapoints && that_present_datapoints))
        return false;
      if (!this.datapoints.equals(that.datapoints))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_datapoints = true && (isSetDatapoints());
    list.add(present_datapoints);
    if (present_datapoints)
      list.add(datapoints);

    return list.hashCode();
  }

  @Override
  public int compareTo(ODSAppValueWithTagsList other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetDatapoints()).compareTo(other.isSetDatapoints());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDatapoints()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.datapoints, other.datapoints);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ODSAppValueWithTagsList(");
    boolean first = true;

    sb.append("datapoints:");
    if (this.datapoints == null) {
      sb.append("null");
    } else {
      sb.append(this.datapoints);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ODSAppValueWithTagsListStandardSchemeFactory implements SchemeFactory {
    public ODSAppValueWithTagsListStandardScheme getScheme() {
      return new ODSAppValueWithTagsListStandardScheme();
    }
  }

  private static class ODSAppValueWithTagsListStandardScheme extends StandardScheme<ODSAppValueWithTagsList> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ODSAppValueWithTagsList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DATAPOINTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list32 = iprot.readListBegin();
                struct.datapoints = new ArrayList<ODSAppValueWithTags>(_list32.size);
                ODSAppValueWithTags _elem33;
                for (int _i34 = 0; _i34 < _list32.size; ++_i34)
                {
                  _elem33 = new ODSAppValueWithTags();
                  _elem33.read(iprot);
                  struct.datapoints.add(_elem33);
                }
                iprot.readListEnd();
              }
              struct.setDatapointsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ODSAppValueWithTagsList struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.datapoints != null) {
        oprot.writeFieldBegin(DATAPOINTS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.datapoints.size()));
          for (ODSAppValueWithTags _iter35 : struct.datapoints)
          {
            _iter35.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ODSAppValueWithTagsListTupleSchemeFactory implements SchemeFactory {
    public ODSAppValueWithTagsListTupleScheme getScheme() {
      return new ODSAppValueWithTagsListTupleScheme();
    }
  }

  private static class ODSAppValueWithTagsListTupleScheme extends TupleScheme<ODSAppValueWithTagsList> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ODSAppValueWithTagsList struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetDatapoints()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetDatapoints()) {
        {
          oprot.writeI32(struct.datapoints.size());
          for (ODSAppValueWithTags _iter36 : struct.datapoints)
          {
            _iter36.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ODSAppValueWithTagsList struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list37 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.datapoints = new ArrayList<ODSAppValueWithTags>(_list37.size);
          ODSAppValueWithTags _elem38;
          for (int _i39 = 0; _i39 < _list37.size; ++_i39)
          {
            _elem38 = new ODSAppValueWithTags();
            _elem38.read(iprot);
            struct.datapoints.add(_elem38);
          }
        }
        struct.setDatapointsIsSet(true);
      }
    }
  }

}

