/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.facebook.maestro;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum OdsDataTable implements org.apache.thrift.TEnum {
  ODS_TABLE_AUTO(0),
  ODS_TABLE_RAW(1),
  ODS_TABLE_WEEK(2),
  ODS_TABLE_MONTH(3),
  ODS_TABLE_YEAR(4),
  ODS_TABLE_CAPACITY(5);

  private final int value;

  private OdsDataTable(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static OdsDataTable findByValue(int value) { 
    switch (value) {
      case 0:
        return ODS_TABLE_AUTO;
      case 1:
        return ODS_TABLE_RAW;
      case 2:
        return ODS_TABLE_WEEK;
      case 3:
        return ODS_TABLE_MONTH;
      case 4:
        return ODS_TABLE_YEAR;
      case 5:
        return ODS_TABLE_CAPACITY;
      default:
        return null;
    }
  }
}
