/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.facebook.maestro;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * an enum that can be used for sql ordering
 */
public enum OdsEntityOrderByType implements org.apache.thrift.TEnum {
  ODS_ENTITY_BY_NAME(0),
  ODS_ENTITY_NONE(1);

  private final int value;

  private OdsEntityOrderByType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static OdsEntityOrderByType findByValue(int value) { 
    switch (value) {
      case 0:
        return ODS_ENTITY_BY_NAME;
      case 1:
        return ODS_ENTITY_NONE;
      default:
        return null;
    }
  }
}
