/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.facebook.maestro;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum OdsExceptionCode implements org.apache.thrift.TEnum {
  ODS_EXCEPTION_DEFAULT(0),
  ODS_EXCEPTION_DBCONN_ERROR(1),
  ODS_EXCEPTION_SQL_ERROR(2),
  ODS_EXCEPTION_DB_NOTFOUND(3),
  ODS_EXCEPTION_SMC_CONN_ERROR(4),
  ODS_EXCEPTION_SMC_DATA_ERROR(5),
  ODS_EXCEPTION_DEPRECIATED_METHOD(6),
  ODS_EXCEPTION_ENTITY_NOT_FOUND(7),
  ODS_EXCEPTION_SERVICE_CONN_ERROR(8),
  ODS_EXCEPTION_KEY_NOT_FOUND(9);

  private final int value;

  private OdsExceptionCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static OdsExceptionCode findByValue(int value) { 
    switch (value) {
      case 0:
        return ODS_EXCEPTION_DEFAULT;
      case 1:
        return ODS_EXCEPTION_DBCONN_ERROR;
      case 2:
        return ODS_EXCEPTION_SQL_ERROR;
      case 3:
        return ODS_EXCEPTION_DB_NOTFOUND;
      case 4:
        return ODS_EXCEPTION_SMC_CONN_ERROR;
      case 5:
        return ODS_EXCEPTION_SMC_DATA_ERROR;
      case 6:
        return ODS_EXCEPTION_DEPRECIATED_METHOD;
      case 7:
        return ODS_EXCEPTION_ENTITY_NOT_FOUND;
      case 8:
        return ODS_EXCEPTION_SERVICE_CONN_ERROR;
      case 9:
        return ODS_EXCEPTION_KEY_NOT_FOUND;
      default:
        return null;
    }
  }
}
