/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.facebook.maestro;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum OdsKeyType implements org.apache.thrift.TEnum {
  ODS_REGULAR_KEY(0),
  ODS_EXCLUDED_KEY(1),
  ODS_INCLUDED_KEY(2),
  ODS_NEW_KEY(3);

  private final int value;

  private OdsKeyType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static OdsKeyType findByValue(int value) { 
    switch (value) {
      case 0:
        return ODS_REGULAR_KEY;
      case 1:
        return ODS_EXCLUDED_KEY;
      case 2:
        return ODS_INCLUDED_KEY;
      case 3:
        return ODS_NEW_KEY;
      default:
        return null;
    }
  }
}
