/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.facebook.maestro;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum OdsTopCriteria implements org.apache.thrift.TEnum {
  ODS_TOP_N_MAX(1),
  ODS_TOP_N_MIN(2),
  ODS_TOP_N_95_PERCENTILE_MAX(3),
  ODS_TOP_N_95_PERCENTILE_MIN(4),
  ODS_TOP_N_AVG_MAX(5),
  ODS_TOP_N_AVG_MIN(6);

  private final int value;

  private OdsTopCriteria(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static OdsTopCriteria findByValue(int value) { 
    switch (value) {
      case 1:
        return ODS_TOP_N_MAX;
      case 2:
        return ODS_TOP_N_MIN;
      case 3:
        return ODS_TOP_N_95_PERCENTILE_MAX;
      case 4:
        return ODS_TOP_N_95_PERCENTILE_MIN;
      case 5:
        return ODS_TOP_N_AVG_MAX;
      case 6:
        return ODS_TOP_N_AVG_MIN;
      default:
        return null;
    }
  }
}
